import Card, { CardBody, CardHeader } from '../../components/ui/Card.jsx';
import { Label } from '../../components/ui/Input.jsx';
import Input from '../../components/ui/Input.jsx';
import Button from '../../components/ui/Button.jsx';
import { Link } from 'react-router-dom';

// Routes are the root of the assignment chain — buses assign themselves to a
// route, drivers assign themselves to a bus, and students assign themselves
// to a route. None of that is editable from here, so this form only ever
// collects the route's own details.
export default function RouteForm({ mode, values, onChange, onSubmit, submitting, routeIdDisplay, error }) {
  const set = (key) => (val) => onChange({ ...values, [key]: val });

  return (
    <form onSubmit={onSubmit}>
      <Card>
        <CardHeader title="Route details" />
        {error && (
          <div className="mx-6 mb-4 rounded-lg border border-red-200 bg-red-50 px-4 py-3 text-sm font-medium text-red-600 dark:border-red-900 dark:bg-red-950/40 dark:text-red-400">
            {error}
          </div>
        )}
        <CardBody className="grid grid-cols-1 gap-5 sm:grid-cols-2">
          <div>
            <Label>Route ID</Label>
            <Input value={routeIdDisplay} disabled placeholder="- Autogenerated" />
          </div>
          <div>
            <Label required>Route name</Label>
            <Input
              value={values.name}
              onChange={(e) => set('name')(e.target.value)}
              placeholder="e.g. West Legon - Ashongman"
              required
            />
          </div>
        </CardBody>

        <div className="flex justify-end gap-3 border-t border-slate-100 p-5 dark:border-slate-800">
          <Button as={Link} to="/routes" variant="outline" type="button">
            Cancel
          </Button>
          <Button type="submit" loading={submitting}>
            {mode === 'edit' ? 'Save Changes' : 'Create Route'}
          </Button>
        </div>
      </Card>
    </form>
  );
}
